### ISSUE TITLE
What is the state of this repository?

### ISSUE THREAD

**Issue by 2color** [nicolas-raoul/OxygenGuide#2]
Is it useable if I want to generate static htmls for conversion to kindle format?

**Comment by nicolas-raoul** [comment]
This repository is usable to generate static HTML.

I don't know about the Kindle format, though. Can Kindle read interlinked static HTML files?

**Comment by 2color** [comment]
> Supported File Types:
Microsoft Word (.DOC, .DOCX)
HTML (.HTML, .HTM)
RTF (.RTF)
JPEG (.JPEG, .JPG)
Kindle Format (.MOBI, .AZW)
GIF (.GIF)
PNG (.PNG)
BMP (.BMP)
PDF (.PDF)

From http://www.amazon.com/gp/sendtokindle/email


I've been playing around with the repo. It seems the script generates multiple files for each article. I'm going to try to get it to the kindle. Thanks for the initial work with the python script.
